{
 "title": "Nodeexport data Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1" },
    { "expr": "node_load5", "legendFormat": "5" },
    { "expr": "node_load15", "legendFormat": "15" }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_Active_bytes)",
     "legendFormat": "Memory free"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Filesystem \"/\""
    }
   ]
  }
 ]
}